### ISSUE TITLE
Where to put SRT C library?

### ISSUE THREAD

**Issue by ivanjaros** [openfresh/gosrt#15]
In the source code I see imports of "srt/srt.h" but there is no such file. If I look at https://github.com/Haivision/srt/blob/master/srtcore/srt.h, which I think is what this is pointing to, the directory structure is different(ie, no "srt" directory in that repo, insted there is "srtcore"). So where should I copy the C library or how should I structure my code?

(I don't use cgo, ever, but i need srt so i don't have much choice).

**Comment by thmatuza** [comment]
If you follow the Readme on srt repository and install it, header files will be located on /usr/local, so CGO can recognize it.
https://github.com/Haivision/srt#for-linux
You may need to set LD_LIBRARY_PATH.

The Dockerfile may be helpful to understand it.
https://github.com/openfresh/gosrt/blob/master/Dockerfile

**Comment by ivanjaros** [comment]
im on windows, do i just git-pull the srtcore directory?

**Comment by thmatuza** [comment]
I am sorry that I have never used Go in windows, I cannot give you much advice.
I guess you need to download strcore into srt folder under this repository root folder.

**Comment by ivanjaros** [comment]
ok, thanks anyway.

**Comment by ivanjaros** [comment]
@thmatuza I am guessing the `/conf` has the `// +build darwin dragonfly freebsd linux netbsd openbsd solaris` on purpose or ....just because?

**Comment by ivanjaros** [comment]
nevermind, the headache is just not worth it.
