### ISSUE TITLE
How to add a callback to authorize streams

### ISSUE THREAD

**Issue by mauricioabreu** [openfresh/gosrt#5]
Thank for this library!

This is not a real issue but a question: How can I add authorization using this library?
I got it working using C but the SRT C API has a callback to pass to the `listen` function.

https://github.com/Haivision/srt/blob/master/docs/AccessControl.md#example

**Comment by thmatuza** [comment]
Hi!
I am sorry for late response.
I just added code for AccessControl to an example program.
https://github.com/openfresh/gosrt/pull/8/files

**Comment by mauricioabreu** [comment]
Thank you @thmatuza 
have a nice day!

**Comment by thmatuza** [comment]
@mauricioabreu I am sorry my previous code was not enough for AccessControl.
It could get streamid but cannot set passphrase before establishing connection.

I just fixed it on this pull request.
https://github.com/openfresh/gosrt/pull/9
